AWSTemplateFormatVersion: 2010-09-09
Description: >-
  EKS En este template se desploya Cluster (solo control plane administrado)

######################
# Parameters section
######################

Parameters:
  MLEKSIdentifier:
    Type: String
    Default: "ML-EKS"

  EndpointPublicAccess0:
    Description: EKS must be public access
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  EndpointPrivateAccess0:
    Description: EKS must be private access
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  PublicAccessCidrs0:
    Description: >-
      Ej: 0.0.0.0/0 - Must be only numbers, dots and slash "/"
    Type: String

  VpcidML:
    Description: VPCs
    Type: AWS::EC2::VPC::Id

  MLEKSSubnets:
    Description: A list of subnets to use when launching EKS
    Type: 'List<AWS::EC2::Subnet::Id>'

  MLEKSSecurityGroup:
    Description: Security Group EKS
    Type: 'List<AWS::EC2::SecurityGroup::Id>'


Resources:

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref MLEKSIdentifier
      Version: "1.21"
      RoleArn: "arn:aws:iam::456441140195:role/LabRole"
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref MLEKSSecurityGroup
        SubnetIds: !Ref MLEKSSubnets
        EndpointPublicAccess: !Ref EndpointPublicAccess0
        EndpointPrivateAccess: !Ref EndpointPrivateAccess0
        PublicAccessCidrs: [ !Ref PublicAccessCidrs0 ]
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
      Tags:
        - Key: "Name"
          Value: "ML-EKS"