repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: python
        types:
          - python
      - id: pylint
        name: pylint
        entry: poetry run pylint *
        language: python
        types:
          - python